spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pharma
    username: root
    password: admin@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5Dialect
  application:
    name: PharmacyService
  kafka:
    producer:
      bootstrap-servers:
      - localhost:9092

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone : http://localhost:8761/eureka

