spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pharma
    username: root
    password: admin@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5Dialect
  application:
    name: ClientService
  main:
    allow-circular-references: true
  kafka:
    consumer:
      auto-offset-reset: earliest
      group-id:  testgroup
      bootstrap-servers:
      - localhost:9092  
  
management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8081
  
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowType: COUNT_BASED
      slidingWindowSize: 100
      permittedNumberOfCallsInHalfOpenState: 10
      waitDurationInOpenState: 10
      failureRateThreshold: 60
      registerHealthIndicator: true
      
